# duplicated
root: / # root_urlpath
admin_dir: itmadmin/ # admin_route
tpl: /user_data/packages/default/ # front_urlpath
admin_tpl: /user_data/packages/admin/ # admin_urlpath
image_path: /upload/save_image/ # image_save_urlpath

# base valiables
root_dir: /vagrant/eccube-3.0.5
root_urlpath: 
template_code: default

# routing
admin_route: itmadmin
user_data_route: user_data

# realdir::image
image_save_realdir: /vagrant/eccube-3.0.5/html/upload/save_image
image_temp_realdir: /vagrant/eccube-3.0.5/html/upload/temp_image

# realdir::user_data
user_data_realdir: /vagrant/eccube-3.0.5/html/user_data

# realdir::block
block_default_realdir: /vagrant/eccube-3.0.5/src/Eccube/Resource/template/default/Block
block_realdir: /vagrant/eccube-3.0.5/app/template/default/Block

# realdir::template
template_default_realdir: /vagrant/eccube-3.0.5/src/Eccube/Resource/template/default
template_default_html_realdir: /vagrant/eccube-3.0.5/html/template/default
template_admin_realdir: /vagrant/eccube-3.0.5/src/Eccube/Resource/template/admin
template_admin_html_realdir: /vagrant/eccube-3.0.5/html/template/admin
template_realdir: /vagrant/eccube-3.0.5/app/template/default
template_html_realdir: /vagrant/eccube-3.0.5/html/template/default
template_temp_realdir: /vagrant/eccube-3.0.5/app/cache/eccube/template

# realdir::csv
csv_temp_realdir: /vagrant/eccube-3.0.5/app/cache/eccube/csv

# realdir:plugin
plugin_realdir: /vagrant/eccube-3.0.5/app/Plugin
plugin_temp_realdir: /vagrant/eccube-3.0.5/app/cache/plugin

# urlpath
admin_urlpath: /template/admin
front_urlpath: /template/default
image_save_urlpath: /upload/save_image
image_temp_urlpath: /upload/temp_image
user_data_urlpath: /user_data
